#!/bin/bash

echo "=========================================="
echo "📤 GitHub 代码推送完整教程"
echo "=========================================="
echo ""
echo "由于需要身份验证，请按以下步骤操作："
echo ""
echo "【步骤1】创建 GitHub 个人访问令牌"
echo "----------------------------------------"
echo "1. 访问：https://github.com/settings/tokens/new"
echo "2. 填写信息："
echo "   - Note: qixi-housekeeping-push"
echo "   - Expiration: 90 days（或选择 No expiration）"
echo "   - Select scopes: 勾选 repo（所有 repo 相关选项）"
echo "3. 点击 'Generate token'"
echo "4. ⚠️ 复制生成的令牌（只显示一次，务必保存）"
echo ""
echo "【步骤2】在终端推送代码"
echo "----------------------------------------"
echo "在终端执行以下命令："
echo ""
echo "cd /workspace/projects"
echo "git push https://你的令牌@github.com/2567764782/qixi-housekeeping.git main"
echo ""
echo "或者使用 SSH 方式："
echo "git remote set-url origin git@github.com:2567764782/qixi-housekeeping.git"
echo "git push -u origin main"
echo ""
echo "=========================================="
echo ""
echo "【方法二】使用 GitHub CLI（更简单）"
echo "----------------------------------------"
echo "1. 安装 GitHub CLI："
echo "   # Windows: 下载 https://cli.github.com/"
echo "   # Mac: brew install gh"
echo "   # Linux: sudo apt install gh"
echo ""
echo "2. 登录："
echo "   gh auth login"
echo ""
echo "3. 推送："
echo "   cd /workspace/projects"
echo "   git push -u origin main"
echo ""
echo "=========================================="
