#!/bin/bash

echo "=========================================="
echo "推送代码到 GitHub 步骤"
echo "=========================================="
echo ""
echo "请按以下步骤操作："
echo ""
echo "1. 在 GitHub 创建一个新仓库（如果还没创建）"
echo "   访问: https://github.com/new"
echo "   仓库名: qixi-housekeeping"
echo "   设置为: Private（私有）或 Public（公开）"
echo "   不要勾选 'Add a README file'"
echo "   点击 'Create repository'"
echo ""
echo "2. 复制仓库地址（类似下面这样）："
echo "   https://github.com/你的用户名/qixi-housekeeping.git"
echo ""
echo "3. 运行以下命令（替换你的用户名）："
echo ""
echo "   cd /workspace/projects"
echo "   git remote add origin https://github.com/你的用户名/qixi-housekeeping.git"
echo "   git add ."
echo "   git commit -m '初始化柒玺家政小程序项目'"
echo "   git branch -M main"
echo "   git push -u origin main"
echo ""
echo "=========================================="
