#!/bin/bash

echo "=========================================="
echo "📤 代码推送解决方案"
echo "=========================================="
echo ""
echo "你的令牌已生成："
echo "ghp_EVvRuDa08VhTJF0J0c6ApDrk1H8pHZ0MNm7z"
echo ""
echo "=========================================="
echo ""
echo "【方案1】使用 GitHub 网页上传（最简单）"
echo "----------------------------------------"
echo "1. 访问你的仓库："
echo "   https://github.com/2567764782/qixi-housekeeping"
echo ""
echo "2. 点击 'uploading an existing file'"
echo ""
echo "3. 把整个项目文件夹拖拽上传"
echo ""
echo "=========================================="
echo ""
echo "【方案2】在本地电脑操作"
echo "----------------------------------------"
echo "1. 下载项目到本地："
echo "   方法A: 在 Coze 平台导出项目"
echo "   方法B: 复制项目文件到本地"
echo ""
echo "2. 在本地终端执行："
echo "   cd 项目目录"
echo "   git init"
echo "   git add ."
echo "   git commit -m '初始化项目'"
echo "   git remote add origin https://github.com/2567764782/qixi-housekeeping.git"
echo "   git push https://ghp_EVvRuDa08VhTJF0J0c6ApDrk1H8pHZ0MNm7z@github.com/2567764782/qixi-housekeeping.git main"
echo ""
echo "=========================================="
echo ""
echo "【方案3】使用 GitHub CLI"
echo "----------------------------------------"
echo "如果你安装了 GitHub CLI："
echo "  gh auth login"
echo "  gh repo clone 2567764782/qixi-housekeeping"
echo "  # 复制文件到仓库"
echo "  git add ."
echo "  git commit -m '初始化项目'"
echo "  git push"
echo ""
echo "=========================================="
