#!/bin/bash

echo "=========================================="
echo "GitHub 仓库设置指南"
echo "=========================================="
echo ""
echo "检测到仓库名包含中文，建议使用英文仓库名"
echo ""
echo "请按以下步骤操作："
echo ""
echo "步骤 1：创建新的 GitHub 仓库（英文命名）"
echo "----------------------------------------"
echo "1. 访问：https://github.com/new"
echo "2. 填写信息："
echo "   Repository name: qixi-housekeeping"
echo "   Description: 柒玺家政小程序"
echo "   选择 Public 或 Private"
echo "   不要勾选任何初始化选项"
echo "3. 点击 'Create repository'"
echo ""
echo "步骤 2：获取仓库地址"
echo "----------------------------------------"
echo "创建后，仓库地址应该是："
echo "https://github.com/2567764782/qixi-housekeeping.git"
echo ""
echo "步骤 3：推送代码"
echo "----------------------------------------"
echo "创建仓库后，告诉我，我会帮你推送代码"
echo ""
echo "=========================================="
