#!/bin/bash

echo "=========================================="
echo "📁 项目文件结构说明"
echo "=========================================="
echo ""
echo "你在 Coze 平台上应该能看到以下文件夹："
echo ""
echo "📂 src/              ← 前端代码文件夹"
echo "   ├── app.config.ts"
echo "   ├── app.tsx"
echo "   ├── pages/        ← 页面文件夹"
echo "   ├── components/   ← 组件文件夹"
echo "   └── network.ts"
echo ""
echo "📂 server/           ← 后端代码文件夹"
echo "   ├── src/"
echo "   ├── database/"
echo "   └── deploy.sh"
echo ""
echo "📂 config/           ← 配置文件夹"
echo "   ├── index.ts"
echo "   ├── dev.ts"
echo "   └── prod.ts"
echo ""
echo "📂 assets/           ← 静态资源文件夹"
echo "   └── image.png"
echo ""
echo "📄 package.json      ← 项目配置文件"
echo "📄 vercel.json       ← 部署配置"
echo "📄 tsconfig.json     ← TypeScript配置"
echo ""
echo "=========================================="
echo ""
echo "⚠️ 注意："
echo "- 这些是文件夹，不是图片"
echo "- 在 Coze 平台的文件列表中查找"
echo "- 文件夹图标通常是黄色的文件夹形状"
echo "- 文件图标通常是白色的文件形状"
echo ""
echo "=========================================="
