#!/bin/bash

echo "=========================================="
echo "🎯 GitHub 令牌生成 - 下一步操作"
echo "=========================================="
echo ""
echo "你当前在：https://github.com/settings/tokens/new"
echo ""
echo "【现在请这样做】"
echo "----------------------------------------"
echo ""
echo "1️⃣ 向下滚动页面"
echo "   找到页面最底部的绿色按钮"
echo ""
echo "2️⃣ 点击绿色按钮"
echo "   按钮文字是：Generate token"
echo "   或者：Generate new token"
echo ""
echo "3️⃣ 等待几秒钟"
echo "   页面会刷新，显示你的令牌"
echo ""
echo "4️⃣ 复制令牌"
echo "   令牌格式：ghp_xxxxxxxxxxxxxxxxxx"
echo "   点击旁边的 Copy 按钮或手动复制"
echo ""
echo "5️⃣ 发送给我"
echo "   直接把令牌发给我"
echo ""
echo "=========================================="
echo ""
echo "⚠️ 如果你看到的是："
echo ""
echo "情况A：页面底部有绿色按钮"
echo "  → 直接点击它"
echo ""
echo "情况B：页面已经显示令牌"
echo "  → 直接复制令牌发给我"
echo ""
echo "情况C：找不到按钮或令牌"
echo "  → 告诉我你在页面看到什么"
echo ""
echo "=========================================="
