export default defineAppConfig({
  pages: [
    'pages/index/index',
    'pages/booking/index',
    'pages/orders/index',
    'pages/profile/index',
    'pages/service-detail/index',
    'pages/contact/index',
    'pages/about/index',
    'pages/privacy/index',
    'pages/terms/index',
    'pages/news/index',
    'pages/news-detail/index',
    'pages/webview/index',
    'pages/login/index',
    'pages/settings/index',
    'pages/auth/index',
    'pages/admin/index',
    'pages/customer-service/index',
    'pages/booking-success/index',
    'pages/my-card/index',
    'pages/recent-activities/index',
    'pages/activity-detail/index',
    'pages/my-registrations/index',
    'pages/activity-notifications/index',
    'pages/qrcode/index',
    'pages/registration/index',
    'pages/hospital-detail/index',
    'pages/booking-confirm/index',
    'pages/create-cleaning-order/index',
    'pages/cleaner-management/index',
    'pages/order-review/index',
    'pages/cleaner-orders/index',
    'pages/statistics/index',
    'pages/payment/index',
    'pages/realtime/index',
    'pages/roles/index',
    'pages/cleaner-apply/index',
    'pages/create-review/index',
    'pages/payment-page/index',
    'pages/membership/index',
    'pages/subscription/index',
    'pages/annual/index',
    'pages/recharge/index',
    'pages/coupon/index',
    'pages/admin-coupon/index',
    'pages/admin-member/index',
    'pages/admin-content/index',
    'pages/hot-news/index',
    'pages/news-manage/index'
  ],
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#fff',
    navigationBarTitleText: '柒玺家政',
    navigationBarTextStyle: 'black'
  },
  tabBar: {
    color: '#B3B3B3',
    selectedColor: '#F85659',
    backgroundColor: '#ffffff',
    borderStyle: 'white',
    list: [
      {
        pagePath: 'pages/index/index',
        text: '首页',
        iconPath: './assets/tabbar/house.png',
        selectedIconPath: './assets/tabbar/house-active.png',
      },
      {
        pagePath: 'pages/orders/index',
        text: '我的预约',
        iconPath: './assets/tabbar/file-text.png',
        selectedIconPath: './assets/tabbar/file-text-active.png',
      },
      {
        pagePath: 'pages/profile/index',
        text: '我的',
        iconPath: './assets/tabbar/user.png',
        selectedIconPath: './assets/tabbar/user-active.png',
      }
    ]
  }
})
